server:
  port:
    5050

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=shortener
    username: postgres
    password: postpost
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    baseline-on-migrate: true
    user: postgres
    password: postpost
    schemas: shortener
    enabled: true

  cache:
    jcache:
      config: "classpath:/cache/cache.xml"

  security:
    user:
      name: user
      password: user
